**Qylle Christian Quiño - DS4A**

*Laboratory Task 5 - Pytorch Exercise*

In [1]:
#1. Perform Standard Imports

import torch
import numpy as np
import sys
import random

In [2]:
#2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.

def set_seed(seed:int):
    random.seed(seed)
    np.random.seed(seed)

set_seed(42)

In [3]:
#3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.

arr = np.random.randint(0,5, size=6)
arr

array([3, 4, 2, 4, 4, 1], dtype=int32)

In [4]:
#4. Create a tensor "x" from the array above

x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [5]:
#5. Change the dtype of x from int32 to int64

x = x.type(torch.int64)
print('New Datatype: ', x.type())

New Datatype:  torch.LongTensor


In [6]:
#6. Reshape x into a 3x2 tensor

reshaped = x.reshape(3,2)
print(reshaped)

tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [7]:
#7. Return the right-hand column of tensor x

reshaped[:,1:]

tensor([[4],
        [4],
        [1]])

In [8]:
#8. Without changing x, return a tensor of square values of x

squared = reshaped ** 2
squared

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [9]:
#9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x

torch.manual_seed(42)
y = torch.rand(3, 2)
print(y)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])


In [10]:
#10. Find the matrix product of x and y.

print(reshaped.mul(y))

tensor([[2.6468, 3.6600],
        [0.7657, 3.8372],
        [1.5618, 0.6009]])
